Document: opendias
Title: Debian opendias Manual
Author: <insert document author here>
Abstract: This manual describes what opendias is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/opendias/opendias.sgml.gz

Format: postscript
Files: /usr/share/doc/opendias/opendias.ps.gz

Format: text
Files: /usr/share/doc/opendias/opendias.text.gz

Format: HTML
Index: /usr/share/doc/opendias/html/index.html
Files: /usr/share/doc/opendias/html/*.html

  
