LOCAL_error_while_updating = '## ##### ####### ##### ######## ### ###########';
LOCAL_error_while_deleting_doc = '## ##### ####### ######## ### ########.';
LOCAL_sure_to_delete_doc = '###### #### ########. ### ### ####?';
LOCAL_default_title = '### (########) ########.';
LOCAL_default_title_warning = '######## ##### ## ##### ### #######';
LOCAL_default_date = ' - ## #### -';
LOCAL_default_date_warning = '######## #### ## ##### ### #######';
LOCAL_no_tags_assigned = '######## ### ### ######## ####';
LOCAL_doc_incomplete_warning = '######## ####### ### ##########';
