-- 
-- Do not edit this file.
-- If you need to update the schema or default data, create a new file 
-- and update the DB version (in the 'version' table and DB_VERSION in src/main.c)
--
BEGIN TRANSACTION;

ALTER TABLE scan_progress 
ADD COLUMN lockexpires;

ALTER TABLE docs
ADD COLUMN actionrequired NUMERIC;

UPDATE version
SET version = 5,
for_app_version = "0.6.4";

COMMIT;

