LOCAL_error_while_updating = 'LOCALISE_ME - An error occurred while updating the information';
LOCAL_error_while_deleting_doc = 'LOCALISE_ME - An error occurred deleting the document.';
LOCAL_sure_to_delete_doc = 'LOCALISE_ME - Delete this document. Are you sure?';
LOCAL_default_title = 'LOCALISE_ME - New (untitled) document.';
LOCAL_default_title_warning = 'LOCALISE_ME - Document Title is still the default';
LOCAL_default_date = 'LOCALISE_ME -  - No date -';
LOCAL_default_date_warning = 'LOCALISE_ME - Document Date is still the default';
LOCAL_no_tags_assigned = 'LOCALISE_ME - Document has not assigned tags';
LOCAL_doc_incomplete_warning = 'LOCALISE_ME - Document details are incomplete';
