-- 
-- Do not edit this file.
-- If you need to update the schema or default data, create a new file 
-- and update the DB version (in the 'version' table and DB_VERSION in src/main.c)
--
BEGIN TRANSACTION;

UPDATE version SET version = 7;

DROP TABLE user_access;

CREATE TABLE user_access (
  username CHAR(36) NOT NULL,
  password CHAR(36) NOT NULL,
  realname CHAR(255) NOT NULL,
  last_access CHAR(255) NOT NULL,
  created CHAR(255) NOT NULL,
  role INTEGER NOT NULL
);

CREATE INDEX user_access_username_idx
ON doc_links(docid ASC);

COMMIT;

