-- 
-- Do not edit this file.
-- If you need to update the schema or default data, create a new file 
-- and update the DB version (in the 'version' table and DB_VERSION in src/main.c)
--
BEGIN TRANSACTION;

UPDATE version SET version = 8;

CREATE TEMPORARY TABLE t1_backup (
  "tagid" INTEGER PRIMARY KEY,
  "tagname" TEXT
);
INSERT INTO t1_backup SELECT tagid, tagname FROM tags;

DROP TABLE tags;
CREATE TABLE tags (
  "tagid" INTEGER PRIMARY KEY,
  "tagname" TEXT,
  "purgephysical" NUMERIC,
  "purgedata" NUMERIC
);

INSERT INTO tags SELECT tagid, tagname, 0, 0 FROM t1_backup;
CREATE UNIQUE INDEX "tagname_idx" ON tags(tagname ASC);

DROP TABLE t1_backup;

COMMIT;

